### ISSUE TITLE
Going to the domain leads to a 500 internal error

### ISSUE THREAD

**Issue by itcodehery** [itcodehery/vox-tech-collective#1]
Recreating the error:
- Go to vox-tech-collective.vercel.app to see the error.
- or build this project by forking this project and using npm run dev.

**Comment by ZEUSGMJ** [comment]
@itcodehery I see that there's a `window is not defined` error. Is that the issue you're facing?

**Comment by ZEUSGMJ** [comment]
@itcodehery I fixed your issue by cloning your repo.

Let me know how you want me to bring the changes/fixes to you.

**Comment by itcodehery** [comment]
> @itcodehery I fixed your issue by cloning your repo.
> 
> Let me know how you want me to bring the changes/fixes to you.

Raise a pull request. You can't raise a pull request by cloning a repo. Clone the fork version and then raise a pull request
